env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download

builds:
  - id: kubefwd
    main: ./cmd/kubefwd/kubefwd.go
    binary: kubefwd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
      - -a
      - -v
    ldflags: -s -w -X main.Version={{.Version}}

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - kubefwd
    dockerfile: Dockerfile.alpine
    builds:
      - kubefwd
    image_templates:
      - "noktoteam/kubefwd:latest"
      - "noktoteam/kubefwd:{{ .Tag }}"
      - "noktoteam/kubefwd:v{{ .Major }}"
      - "noktoteam/kubefwd:amd64-{{ .Tag }}"
      - "noktoteam/kubefwd:amd64-v{{ .Major }}"
      - "noktoteam/kubefwd:latest_alpine-3"
      - "noktoteam/kubefwd:{{ .Tag }}_alpine-3"
      - "noktoteam/kubefwd:v{{ .Major }}_alpine-3"
      - "noktoteam/kubefwd:amd64-{{ .Tag }}_alpine-3"
      - "noktoteam/kubefwd:amd64-v{{ .Major }}_alpine-3"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - kubefwd
    dockerfile: Dockerfile.ubuntu
    builds:
      - kubefwd
    image_templates:
      - "noktoteam/kubefwd:latest_ubuntu-20.04"
      - "noktoteam/kubefwd:{{ .Tag }}_ubuntu-20.04"
      - "noktoteam/kubefwd:v{{ .Major }}_ubuntu-20.04"
      - "noktoteam/kubefwd:amd64-{{ .Tag }}_ubuntu-20.04"
      - "noktoteam/kubefwd:amd64-v{{ .Major }}_ubuntu-20.04"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/noktoteam/kubefwd
    description: Kubernetes bulk port forwarding utility (fork txn2/kubefwd)
    maintainer: Nick Cooper
    license: Apache 2.0
    vendor: https://github.com/noktoteam
    formats:
      - apk
      - deb
      - rpm
    recommends:
      - kubectl

release:
  github:
    owner: noktoteam
    name: kubefwd
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

brews:
  - name: kubefwd
    tap:
      owner: noktoteam
      name: homebrew-tap
    commit_author:
      name: Nick Cooper
      email: nick@nokto.ai
    folder: Formula
    homepage: https://github.com/noktoteam/kubefwd
    description: "Kubernetes bulk port forwarding utility."
    skip_upload: false
    dependencies:
      - name: kubectl
        type: optional
    test: |-
      kubefwd version
